name: Build ActionClips
on: push

jobs:
  Build-ActionClips:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v2
      - name: Print current directory
        run: pwd
      - name: List files in directory
        run: ls
      - name: Check dotnet version
        run: dotnet --version
      - name: .NET Build
        run: dotnet build
      - name: Check NPM
        run: npm --v